### ISSUE TITLE
When invalid file is uploaded, file is not loaded but is still uploaded

### ISSUE THREAD

**Issue by collin-lyon** [Jonathan5122827/ImageProc#10]
When invalid file is uploaded, it is not loaded to canvas, but it is uploaded. After it is uploaded, and we realize it is not valid, the file upload should be emptied. This can be likely be done by setting it to null.

**Comment by collin-lyon** [comment]
This is a functional bug, as it is related to Open Image functionality, a FR.

**Comment by kalvingarcia** [comment]
The issue reported about file upload. The file will always be uploaded there is no way to confirm the file to be an image without uploading it. All we can do is clear the value and not load the image. The function is already not loading without a match, so I added the clear, hopefully.
