### ISSUE TITLE
File spoofing vulnerability.

### ISSUE THREAD

**Issue by collin-lyon** [Jonathan5122827/ImageProc#5]
Currently, there is no way to confirm that an uploaded picture is actually a picture, and not some other file artificially given a picture file type. This can be probably be fixed using a 'mime type' library, which could read the header of the data to confirm that the file type is real.

**Comment by collin-lyon** [comment]
This is a functional requirement, as it is related to open image, a FR.

**Comment by kalvingarcia** [comment]
Fixed this one too, hopefully!
